export const MUSCLE_GROUP = {
  CHEST: 'CHEST',
  BACK: 'BACK',
  LEGS: 'LEGS',
  ARMS: 'ARMS',
  SHOULDERS: 'SHOULDERS',
  CORE: 'CORE',
  CALVES: 'CALVES',
  GLUTES: 'GLUTES',
  POSTERIOR_LEGS: 'POSTERIOR_LEGS',
  QUADRICEPS: 'QUADRICEPS',
  BICEPS: 'BICEPS',
  TRICEPS: 'TRICEPS',
  TRAPEZIUS: 'TRAPEZIUS',
  LUMBAR: 'LUMBAR',
  FOREARMS: 'FOREARMS',
  OTHER: 'OTHER',
};

export const MUSCLE_GROUP_LABEL = {
  CHEST: 'Peito',
  BACK: 'Costas',
  LEGS: 'Pernas',
  ARMS: 'Braços',
  SHOULDERS: 'Ombros',
  CORE: 'Abdômen/Core',
  CALVES: 'Panturrilhas',
  GLUTES: 'Glúteos',
  POSTERIOR_LEGS: 'Posterior das Pernas',
  QUADRICEPS: 'Quadríceps',
  BICEPS: 'Bíceps',
  TRICEPS: 'Tríceps',
  TRAPEZIUS: 'Trapézio',
  LUMBAR: 'Lombar',
  FOREARMS: 'Antebraços',
  OTHER: 'Outro',
};
